### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by pierrealexandre7** [pierrealexandre7/use-all-the-selectors#1]
[Screen Shot 2021-03-14 at 6.5.pdf](https://github.com/pierrealexandre7/use-all-the-selectors/files/6137810/Screen.Shot.2021-03-14.at.6.5.pdf)

I am having difficulty understanding how to make a css of an attribute link.

@hellachella

**Comment by hellachella** [comment]
You just need to add the boilerplate css.

```
html {
  box-sizing: border-box;
}

*, *::before, *::after {
  box-sizing: inherit;
}
```
